name: test-setup-melange

on:
  pull_request:

jobs:
  test-setup-melange:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    - id: changed-melange
      uses: tj-actions/changed-files@8238a4103220c636f2dad328ead8a7c8dbe316a3 # v39.2.0
      with:
        files: |
          ./setup-melange/**
          ./melange-build/**
          ./melange-build-pkg/**
          ./melange-keygen/**
          .github/workflows/test-setup-melange.yaml

    - uses: ./setup-melange
      if: steps.changed-melange.outputs.any_changed == 'true'

    - if: steps.changed-melange.outputs.any_changed == 'true'
      run: |
        melange build setup-melange/example/melange.yaml --arch=x86_64
        ls -R packages/

  # This should do the same thing.
  test-melange-build:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - id: changed-melange
        uses: tj-actions/changed-files@8238a4103220c636f2dad328ead8a7c8dbe316a3 # v39.2.0
        with:
          files: |
            ./setup-melange/**
            .github/workflows/test-setup-melange.yaml

      - uses: ./melange-build
        if: steps.changed-melange.outputs.any_changed == 'true'
        with:
          config: setup-melange/example/melange.yaml
          archs: x86_64
          sign-with-temporary-key: true
